name: 🔁 RunParsers

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths-ignore:
            - "docs/**"
        # - 'luxembourg/**'
    schedule:
        - cron: "31 6,8 * * *" # UTC
        - cron: "59 23 * * 0" # Run once sunday night

concurrency:
    group: parsers-${{ github.ref }}
    cancel-in-progress: true

jobs:
    generateXMLFeeds:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            - uses: actions/checkout@v4
            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - name: Install package.json
              run: |
                  npm install
            - name: Run parsers & update xml feeds
              run: |
                  npm run start
            - name: Upload feeds as artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: docs
    deployPages:
        needs: generateXMLFeeds
        permissions:
            pages: write
            id-token: write
        environment:
            name: gh-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub pages
              id: deployment
              uses: actions/deploy-pages@v3
