name: 🔁 RunParsers

on:
    # push:
    #     branches: [main]
    #     paths-ignore:
    #     - "docs/**"
    #     - 'luxembourg/**'
    schedule:
        - cron: "0 6 * * 1" # Run on Monday, 6:00 (to check if full run is due or not)
        - cron: "0 6 * * 0,2-6" # Run 6:00 every day except monday
    workflow_dispatch:
        inputs:
            type:
                description: Run Type
                required: true
                default: full
                type: choice
                options:
                    - full
                    - partial

concurrency:
    group: parsers-${{ github.ref }}
    cancel-in-progress: true

jobs:
    generateXMLFeeds:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            BASE_URL: https://maxetmoritz.github.io/openMensaMax
        steps:
            - uses: actions/checkout@v4
            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"
            - name: Install package.json
              run: |
                  npm install
            - name: Restore feed cache # only for partial runs, to preserve full feeds.
              if: inputs.type == 'partial' || github.event.schedule == '0 6 * * 0,2-6'
              uses: actions/cache/restore@v4
              with:
                  key: feed-cache
                  path: pages/feeds/*.xml
            - name: Run full parsers
              if: inputs.type == 'full' || github.event.schedule == '0 6 * * 1'
              run: |
                  npm run start:allweeks
            - name: Run today parsers only
              if: inputs.type == 'partial' || github.event.schedule == '0 6 * * 0,2-6'
              run: |
                  npm run start
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Build
              uses: actions/jekyll-build-pages@v1
              with:
                source: ./pages
                destination: ./pages/_site
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./pages/_site
            - name: Delete old feed cache
              if: inputs.type == 'full' || github.event.schedule == '0 6 * * 1'
              run: |
                  set +e
                  echo "Deleting caches..."
                  gh cache delete feed-cache
                  echo "Done."
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}
                BRANCH: ${{ github.ref | 'refs/heads/main' }}
            - name: Save new feed cache # only for full runs.
              if: inputs.type == 'full' || github.event.schedule == '0 6 * * 1'
              uses: actions/cache/save@v4
              with:
                  key: feed-cache
                  path: pages/feeds/*.xml
    deployPages:
        needs: generateXMLFeeds
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub pages
              id: deployment
              uses: actions/deploy-pages@v4

    workflow-keepalive:
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
            - uses: liskin/gh-workflow-keepalive@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
